<?php
 $orderData=$this->getOrderData();
 //print_r($orderData);
 $secretAndUrl=$this->getOrderData();
 $url=$secretAndUrl['redirectUrl'];
 $secret= $secretAndUrl['secret'];
 unset( $orderData["secret"], $orderData["redirectUrl"]);
$serial = json_encode($orderData,JSON_UNESCAPED_SLASHES);
//print_r($serial);die;
$sign = hash('sha256', $serial.$secret );
?>
<form name="scuolapayform" id="scuolapayment" method="POST" action="<?= $url; ?>/session" style="display:none;">
 <input type="hidden" name="business" value="<?=$orderData['business']?>"/>
 <input type="hidden" name="amount" value="<?=$orderData['amount']?>"/>
 <input type="hidden" name="orderId" value="<?=$orderData['orderId']?>"/>
 <input type="hidden" name="responseURL" value="<?=$orderData['responseURL']?>"/>
 <input type="hidden" name="webhookURL" value="<?=$orderData['webhookURL']?>"/>
<input type="hidden" name="sign" value="<?php echo $sign; ?>"/>
 <input type="submit" value="PAGA CON SCUOLAPAY">
</form>
<p>Please wait</p>
<div id="vl-overlay"><div class="loader"></div></div>
<script type="text/javascript">
    require([ 'jquery', 'jquery/ui'], function($){ 
          $("#scuolapayment").submit();
    });
</script>
<style>
#vl-overlay {
    width: 100%!important;
    height: 100%!important;
    left: 0!important;
    top: 0!important;
    position: fixed!important;
    background: #000!important;
    opacity: .7!important;
    z-index: 2147483646!important;
}.loader {
    border: 10px solid #f3f3f3;
    border-radius: 50%;
    border-top: 10px solid grey;
    width: 20px;
    height: 20px;
    position: fixed;
    margin: 0 auto;
    -webkit-animation: spin 2s linear infinite;
    top: 50%;
    right: 0;
    left: 0;
    /* bottom: 0; */
    animation: spin 2s linear infinite;
}

/* Safari */
@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
footer.page-footer,.copyright{display:none;}
</style>